# Generated by Django 4.2.5 on 2023-09-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='track',
        ),
    ]
